[project]
name = "prexsyn-engine"
dynamic = ["version"]
requires-python = ">=3.11"
authors = [{ name = "Shitong Luo", email = "luost26@gmail.com" }]
readme = "README.md"
license-files = ["LICENSE"]

[tool.setuptools.dynamic]
version = { attr = "prexsyn_engine.__version__" }

[tool.ruff]
line-length = 119
target-version = "py311"

[tool.ruff.lint.pyflakes]
allowed-unused-imports = ["rdkit.Chem"]

[tool.pyright]
typeCheckingMode = "strict"
include = ["prexsyn_engine"]

[tool.bumpversion]
current_version = "0.1.0"

[[tool.bumpversion.files]]
filename = "prexsyn_engine/__init__.py"
search = '__version__ = "{current_version}"'
replace = '__version__ = "{new_version}"'

[[tool.bumpversion.files]]
filename = "rattler-recipe/recipe.yaml"
search = 'version: {current_version}'
replace = 'version: {new_version}'

[[tool.bumpversion.files]]
filename = "stub-pkg/pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'
